spring:
  jpa:
    database: "POSTGRESQL"
    driverClassName: "org.postgresql.Driver"
    properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
  datasource:
    platform: "postgres"
    show-sql: "true"
    datasource.url: "jdbc:postgresql://database:5432/eagle_eye_local"
    username: "postgres"
    password: "p0stgr@s"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"